# Generated by Django 2.1 on 2018-08-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccount',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
